### ISSUE TITLE
JWE encryption for entire payload where request and response objects are different

### ISSUE THREAD

**Issue by sumanguduru** [Mastercard/client-encryption-nodejs#65]
**Description**

> When encrypting the entire payload and assigning it to encryptedData, and subsequently making an API call, the response is received as an encryptedResponse object. In this case, while decrypting response object an error is thrown throw new Error("Input not valid");.

**To Reproduce**

**JWE Config**
```
{
"path": "/entirepayload",
"toEncrypt": [{ "element": "$", "obj": "$" }],
"toDecrypt": [{ "element": "encryptedResponse", "obj": "$" }],
"mode": "JWE",
"encryptedValueFieldName": "encryptedData",
"publicKeyFingerprintType": "certificate",
"dataEncoding": "base64",
"encryptionCertificate": "./test/res/test_certificate.cert",
keyStore: "./pkcs8_private_key.pem"
}
```

**Request payload**
```
const payload = {
        sensitive: "this is a secret!",
        sensitive2: "this is a super-secret!",
    }
```
  
**Encrypt the request**
```
const jwe = new (require("mastercard-client-encryption").JweEncryption)(config);
let encryptedData = jwe.encrypt("/entirepayload", null, payload);
```

**_Now, Data is encrypted as below which is expecte_**
```
{
  header: null,
  body: {
    encryptedData: 'eyJraWQiOiIxMDc3ZDIyMTk0Y2MyNzFkNTY1Y2Y2Mjg5YzJiMjY1Y2U4MDhhNDdlMDFiMzhiMjIyZWE4YWU4M2U5MWUxN2Q2IiwiY3R5IjoiYXBwbGljYXRpb24vanNvbiIsImFsZyI6IlJTQS1PQUVQLTI1NiIsImVuYyI6IkEyNTZHQ00ifQ.VaUDfEwds7/kQdQdhpQllSxAhCQrnILDHIF4dY6U-9D8Jg33rLkQMYRzNmEwA14KE0zNVqy2-r6yZ8U7wuksSap9K7jVdhF2XZmW-ytYedS79bOVWe3euNUvHgFSEVt53J67Ca80p8B6x9EeJnYcvQhHVkumVD-QEpb3sk0dIUfo29LVugxKrdJDYKECtXjV1BYrZY0aZ26k-RcqyJdngFphknRDdQpXves4dV3A7qvBHXe65aNrKOUMTpIJ4iTGSNGj4/ismrMj3OENx4aBuLA9igVZgpTEaX1IPwmpIBir/Zl/ZcV567i2FcUoFfjNt63olIMnd4axGwvM3/QPug.ez7IRvsts3LETjGJNU2HgA.OApjJMlmPacg1pdySaFwMrknJ/USUVdFB9dCvwypxPvescKuGkyL-aZNtr307YYF0GmxzBVQ9ZS7wdRSW8xzm6NdCyqmiHEe.7VSy2mfxi5JDLieN135A2A'
  }
}
```

**When I send the encryptedData to my API, It will return the response object as encryptedResponse, as shown below.**
_You can simulate the API behavior like below._
encryptedData.body.encryptedResponse = encryptedData.body.encryptedData;
delete encryptedData.body.encryptedData;
```

   body: {
    encryptedResponse: 'eyJraWQiOiIxMDc3ZDIyMTk0Y2MyNzFkNTY1Y2Y2Mjg5YzJiMjY1Y2U4MDhhNDdlMDFiMzhiMjIyZWE4YWU4M2U5MWUxN2Q2IiwiY3R5IjoiYXBwbGljYXRpb24vanNvbiIsImFsZyI6IlJTQS1PQUVQLTI1NiIsImVuYyI6IkEyNTZHQ00ifQ.VaUDfEwds7/kQdQdhpQllSxAhCQrnILDHIF4dY6U-9D8Jg33rLkQMYRzNmEwA14KE0zNVqy2-r6yZ8U7wuksSap9K7jVdhF2XZmW-ytYedS79bOVWe3euNUvHgFSEVt53J67Ca80p8B6x9EeJnYcvQhHVkumVD-QEpb3sk0dIUfo29LVugxKrdJDYKECtXjV1BYrZY0aZ26k-RcqyJdngFphknRDdQpXves4dV3A7qvBHXe65aNrKOUMTpIJ4iTGSNGj4/ismrMj3OENx4aBuLA9igVZgpTEaX1IPwmpIBir/Zl/ZcV567i2FcUoFfjNt63olIMnd4axGwvM3/QPug.ez7IRvsts3LETjGJNU2HgA.OApjJMlmPacg1pdySaFwMrknJ/USUVdFB9dCvwypxPvescKuGkyL-aZNtr307YYF0GmxzBVQ9ZS7wdRSW8xzm6NdCyqmiHEe.7VSy2mfxi5JDLieN135A2A'
  }
```

Now, when I try to decrypt the encrypted response I get below error
```
const response = {};
response.request = { url: "/entirepayload" };
response.body =encryptedData.body;
let decryptedPayload = jwe.decrypt(response);
```

```
mastercard-client-encryption/lib/mcapi/crypto/jwe-crypto.js:103
      throw new Error("Input not valid");
      ^

Error: Input not valid
    at JweCrypto.decryptData (/Users//Workspace/temp/test-jwe/node_modules/mastercard-client-encryption/lib/mcapi/crypto/jwe-crypto.js:103:13)
    at JweEncryption.decryptBody (/Users//Workspace/temp/test-jwe/node_modules/mastercard-client-encryption/lib/mcapi/encryption/jwe-encryption.js:88:38)
    at /Users//Workspace/temp/test-jwe/node_modules/mastercard-client-encryption/lib/mcapi/encryption/jwe-encryption.js:53:26
    at Array.map (<anonymous>)
    at JweEncryption.decrypt (/Users/Workspace/temp/test-jwe/node_modules/mastercard-client-encryption/lib/mcapi/encryption/jwe-encryption.js:52:35)
    at Object.<anonymous> (/Users//Workspace/temp/test-jwe/app.js:61:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

**Additional context**
Add any other context about the problem here (OS, language version, etc..).

**Related issues/PRs**
PR: (https://github.com/Mastercard/client-encryption-nodejs/pull/64)

**Comment by NehaSony** [comment]
Hi @sumanguduru 
Thanks for raising this issue. We will investigate this and get back to you shortly.

**Comment by NehaSony** [comment]
Hi @sumanguduru 
Creating two different configs, one for encryption and the other for decryption can help you fix this.  

JWE Config for decryption
```
{
"encryptedValueFieldName": "encryptedResponse",
}
```
And then use this as 

```
const decryption = new JweEncryption(DecryptionConfig);
```

**Comment by sumanguduru** [comment]
@NehaSony  how do you handle the interceptor with two different configs. JAVA and Python working fine why this is different.
https://github.com/Mastercard/client-encryption-nodejs/blob/main/lib/mcapi/mcapi-service.js#L20

**Comment by NehaSony** [comment]
Hi @sumanguduru 

One way you can handle this is by having different instances like those described below:

encryptPayload usage:
```
const jweEncryp = new clientEncryption.JweEncryption(encryptConfig);
// …
let encryptedRequestPayload = jweEncryp.encrypt(endpoint, header, body);
```

decryptPayload usage:
```
const jweDecrypt = new clientEncryption.JweEncryption(decryptConfig);
// …
let responsePayload = jweDecrypt.decrypt(encryptedResponsePayload);
```
We try to keep the usage of each language as close to each other as possible.  The implementation of each may slightly differ due to dependencies of the language. 

If you have any suggestions to improve the experience feel free to contribute.
